name: Jekyll Bulma
description: "Jekyll Bulma Theme, Bulma.io CSS Framework Jekyll Template for Developers"
baseurl: /jekyll-bulma
url: http://erayaydin.github.io
download: "https://github.com/erayaydin/jekyll-bulma/archive/master.zip"
social:
  github: erayaydin
  email: aydineray@mail.com
  facebook:
  twitter: erayaydi
  instagram:
  tumblr:
author:
  name: Eray AYDIN
  bio: "Senior PHP Developer and Linux System Administrator, Free Software Fan, Archy (On Way Trust User), Junior Game Developer"
  email: aydineray@mail.com
  image: /assets/images/author.jpg
  github: erayaydin
  facebook: erayaydi
  twitter: erayaydi
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
