name: Edgar Blog
description: "我的零散笔记"
baseurl: /
url: http://edgar615.github.io
download: "#"
social:
  github: edgar615
  email: 67672283@qq.com
  facebook:
  twitter: 
  instagram:
  tumblr:
author:
  name: Edgar
  bio: "Java Developer"
  email: 67672283@qq.com
  image: /assets/images/author.jpg
  github: edgar615
  facebook: 
  twitter: 
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
