name: Edgar Blog
description: "我的零散笔记"
baseurl: /
url: http://edgar615.github.io
download: "https://github.com/edgar615/edgar615.github.io/archive/master.zip"
social:
  github: edgar615
  email: 67672283@qq.com
  facebook:
  twitter: 
  instagram:
  tumblr:
author:
  name: Eray AYDIN
  bio: "Senior PHP Developer and Linux System Administrator, Free Software Fan, Archy (On Way Trust User), Junior Game Developer"
  email: aydineray@mail.com
  image: /assets/images/author.jpg
  github: erayaydin
  facebook: erayaydi
  twitter: erayaydi
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
